### ISSUE TITLE
Is the training code only support "batch size=1"?

### ISSUE THREAD

**Issue by If-only1** [mli0603/stereo-transformer#51]
Hi @mli0603, at first thanks for open source codes!!!
but when I want to use the code with a larger batchsize to train , it's seem to have some bugs in the codes. 
even though I removed the randomcrop, to make sure each img in a batch is the same shape ,  I still get som errors like below:
`Traceback (most recent call last):
  File "train_multi_dataset.py", line 253, in <module>
    main(args_)
  File "train_multi_dataset.py", line 222, in main
    args.clip_max_norm, amp)
  File "/home/hadoop-uavcvml/cephfs/data/lixianyang/stereo_match_lxy/STTR/utilities/train.py", line 32, in train_one_epoch
    _, losses, sampled_disp = forward_pass(model, data, device, criterion, train_stats)
  File "/home/hadoop-uavcvml/cephfs/data/lixianyang/stereo_match_lxy/STTR/utilities/foward_pass.py", line 55, in forward_pass
    outputs = model(inputs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hadoop-uavcvml/cephfs/data/lixianyang/stereo_match_lxy/STTR/module/sttr.py", line 97, in forward
    attn_weight = self.transformer(feat_left, feat_right, pos_enc)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hadoop-uavcvml/cephfs/data/lixianyang/stereo_match_lxy/STTR/module/transformer.py", line 110, in forward
    attn_weight = self._alternating_attn(feat, pos_enc, pos_indexes, hn)
  File "/home/hadoop-uavcvml/cephfs/data/lixianyang/stereo_match_lxy/STTR/module/transformer.py", line 79, in _alternating_attn
    pos_indexes)
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/checkpoint.py", line 163, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/usr/local/lib64/python3.6/site-packages/torch/utils/checkpoint.py", line 74, in forward
    outputs = run_function(*args)
  File "/home/hadoop-uavcvml/cephfs/data/lixianyang/stereo_match_lxy/STTR/module/transformer.py", line 74, in custom_cross_attn
    return module(*inputs, False)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hadoop-uavcvml/cephfs/data/lixianyang/stereo_match_lxy/STTR/module/transformer.py", line 185, in forward
    pos_indexes=pos_indexes)[0]
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hadoop-uavcvml/cephfs/data/lixianyang/stereo_match_lxy/STTR/module/attention.py", line 89, in forward
    k = k.contiguous().view(-1, bsz, self.num_heads, head_dim)
RuntimeError: shape '[-1, 1440, 8, 16]' is invalid for input of size 2359296`

**Comment by If-only1** [comment]
@mli0603,I also noticed that the code uses **batch norm** to implement **instance norm**, does it means this code only supports **batchsize=1**

**Comment by mli0603** [comment]
Yes, the code currently only supports batch=1 for several reasons. You need some tweaking to get it work with multiple batches.

**Comment by If-only1** [comment]
ok, thanks  for you answer.

**Comment by If-only1** [comment]
> Yes, the code currently only supports batch=1 for several reasons. You need some tweaking to get it work with multiple batches.
ok, thanks for your answer.

**Comment by Magicboomliu** [comment]
@If-only1  I found the same issues. Could you please show me how to revise the Code, so that can make the code training on multiple patches?
