### ISSUE TITLE
undefined symbol: mkl_sparse_z_bsr_ng_avx521_sp_mv_i4

### ISSUE THREAD

**Issue by MichaelWangGo** [mli0603/stereo-transformer#92]
Hi authors,

Thanks for sharing the code, you really did an excellent job!

But when I execute `sh scripts/kitti_finetune.sh`, an error ouputs:
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from dataset import build_data_loader
  File "/workspace/michael/data/stereo-transformer/dataset/__init__.py", line 7, in <module>
    from dataset.kitti import KITTI2015Dataset, KITTI2012Dataset, KITTIDataset
  File "/workspace/michael/data/stereo-transformer/dataset/kitti.py", line 10, in <module>
    from albumentations import Compose
  File "/opt/conda/envs/sttr/lib/python3.6/site-packages/albumentations/__init__.py", line 5, in <module>
    from .augmentations import *
  File "/opt/conda/envs/sttr/lib/python3.6/site-packages/albumentations/augmentations/__init__.py", line 2, in <module>
    from .blur.functional import *
  File "/opt/conda/envs/sttr/lib/python3.6/site-packages/albumentations/augmentations/blur/__init__.py", line 1, in <module>
    from .functional import *
  File "/opt/conda/envs/sttr/lib/python3.6/site-packages/albumentations/augmentations/blur/functional.py", line 5, in <module>
    import cv2
  File "/root/.local/lib/python3.6/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/root/.local/lib/python3.6/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/opt/conda/envs/sttr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/local/lib/libmkl_sequential.so.1: undefined symbol: mkl_sparse_z_bsr_ng_avx521_sp_mv_i4

So, how to fix this problem?

Thanks in advance.

**Comment by MichaelWangGo** [comment]
ok, the problem has been fixed, just replacing another version of cv2...

By the way, how to get occ_left from SCARED dataset?
